theme: jekyll-theme-minimal
title: Ilya Lytkin Resume
description: This site shows a shortened version of my resume that you can find on LinkedIn and HeadHunter.
logo: /assets/img/lytkini_transparent.png