swagger: '2.0'
info:
  $ref: ./evotorRstAoi/info.yaml
tags:
  - name: Сущности пользователя Эвотор
    description:
      Запросы информации о магазинах, сотрудниках и смарт-терминалах определённого пользователя платформы Эвотор.
  - name: Товары и документы
    description:
      Запросы информации об определённом магазине (`storeUuid`) пользователя платформы Эвотор.
produces:
    - application/json
consumes:
    - application/json
host: api.evotor.ru
schemes:
    - https
paths:
  $ref:  ./evotorRstApi/paths.yaml
parameters:
  $ref:  ./evotorRstApi/parameters.yaml
definitions:
  $ref:  ./evotorRstApi/definitions.yaml
