swagger: '2.0'
info:
  $ref: ./evotorRestApi/info.yaml
tags:
  - name: Сущности пользователя Эвотор
    description:
      Запросы информации о магазинах, сотрудниках и смарт-терминалах определённого пользователя платформы Эвотор.
  - name: Товары и документы
    description:
      Запросы для работы с товарами и документами пользователя платформы Эвотор.
      Все запросы выполняются в рамках определённого магазина (`storeUuid`).
  - name: Вебхуки-запросы
    description:
      Запросы к стороннему сервису. Облако Эвотор ожидает подтверждения этих запросов. Время ожидания -- 10 секунд.
  - name: Вебхуки-уведомления
    description:
      События, на которые сторонний сервис может подписаться. Облако Эвотор не ожидает ответа на эти события
  - name: Новый тег
    description:
      Работа с дополнительными полями и схемами продуктов.
produces:
    - application/json
consumes:
    - application/json
x-servers:
  - url: //
    description: 'Веб-адрес запроса:'
schemes:
    - https
paths:
  $ref: ./evotorRestApi/paths.yaml
parameters:
  $ref: ./evotorRestApi/parameters.yaml
definitions:
  $ref: ./definitions.yaml
