swagger: '2.0'
info:
  $ref: ./info/index.yaml
tags:
  - name: Сущности пользователя Эвотор
    description:
      Запросы информации о магазинах, сотрудниках и смарт-терминалах определённого пользователя платформы Эвотор.
  - name: Товары и документы
    description:
      Запросы информации об определённом магазине (`storeUuid`) пользователя платформы Эвотор.
produces:
  - application/json
consumes:
  - application/json
host: api.evotor.ru
schemes:
  - https
paths:
  $ref: ./paths/index.yaml
parameters:
  $ref: ./parameters/index.yaml
definitions:
  $ref: ./definitions/index.yaml
