# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Документация Эвотор
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: О платформе Эвотор
    output: web, pdf
    folderitems:

    - title: Введение
      url: /p1_introduction.html
      output: web, pdf

    - title: Тестирование приложения
      url: /p1_application_test.html
      output: web, pdf

    - title: Термины и определения
      url: /p1_terms_and_definitions.html
      output: web, pdf

  - title: Интеграция с платформой
    output: web, pdf

    folderitems:
    - title: История изменений API и SDK
      url: /p1_changes_history.html
      output: web, pdf

    - title: Запросы к облаку Эвотор
      url: /p1_evotor_rest_api_calls.html
      output: web, pdf

    - title: Запросы к стороннему сервису
      url: /p1_outgoing_calls_protocol.html
      output: web, pdf

    - title: Приложения для смарт-терминала
      url: /p1_smart_terminal_applications.html
      output: web, pdf

    - title: Документы смарт-терминала
      url: /p1_smart_terminal_documents.html
      output: web, pdf

    - title: Возвращаемые ошибки
      url: /p1_errors_returned.html
      output: web, pdf

  - title: Примеры реализации
    output: web, pdf

    folderitems:
    - title: Облачная товароучётная система
      url: /p1_cloud_server_to_server.html
      output: web, pdf

    - title: IFrame на странице приложения
      url: /p1_iframe_within_application_page.html
      output: web, pdf

    - title: Приложение для смарт-терминала
      url: /p1_smart_terminal_application.html
      output: web, pdf

    - title: Интеграция с 1С
      url: /p1_1C_integration.html
      output: web, pdf

  - title: SDK смарт-терминала
    output: web, pdf
    folderitems:

    - title: Описание SDK смарт-терминала
      url: /doc_smart_terminal_sdk.html
      output: web

  - title: Продажа
    output: web, pdf
    folderitems:

    - title: Юридическая схема
      url: /p1_legal_scheme.html
      output: web, pdf

    - title: Тарифы приложений
      url: /p1_applications_tariffs.html
      output: web, pdf

    - title: Условия
      url: /p1_conditions.html
      output: web, pdf

    - title: Продвижение
      url: /p1_marketing.html
      output: web, pdf

  - title: FAQ
    output: web, pdf
    folderitems:
    - title: FAQ
      url: /p1_faq.html
      output: web
